; NUMBERTILES.Z80
;
; Tile Source File.
;
; Info:
;   Section              : Tiles
;   Bank                 : 0
;   Form                 : All tiles as one unit.
;   Format               : Gameboy 4 color.
;   Compression          : None.
;   Counter              : None.
;   Tile size            : 8 x 8
;   Tiles                : 0 to 9
;
;   Palette colors       : None.
;   SGB Palette          : None.
;   CGB Palette          : None.
;
;   Convert to metatiles : No.
;
; This file was generated by GBTD v2.2
;numbers 1-9, 0

; Start of tile array.
NumberTiles:
DB $00,$00,$1C,$18,$3C,$28,$0C,$08
DB $0C,$08,$0C,$08,$0C,$08,$3E,$3C
DB $00,$00,$1C,$18,$3E,$24,$06,$04
DB $06,$04,$1C,$18,$38,$20,$3E,$3C
DB $00,$00,$3C,$38,$3E,$04,$06,$04
DB $3C,$38,$3E,$04,$06,$04,$3C,$38
DB $00,$00,$36,$24,$36,$24,$36,$24
DB $3E,$1C,$1E,$04,$06,$04,$06,$04
DB $00,$00,$3E,$3C,$3C,$20,$30,$20
DB $3E,$1C,$06,$04,$36,$24,$3C,$18
DB $00,$00,$1E,$1C,$3C,$20,$30,$20
DB $38,$38,$3C,$24,$34,$24,$3C,$18
DB $00,$00,$3E,$3C,$3E,$04,$06,$04
DB $06,$04,$0C,$08,$18,$10,$18,$10
DB $00,$00,$1C,$18,$3E,$24,$36,$24
DB $3C,$18,$3E,$24,$36,$24,$3C,$18
DB $00,$00,$1C,$18,$3E,$24,$36,$24
DB $3E,$1C,$06,$04,$06,$04,$06,$04
DB $00,$00,$1C,$18,$3E,$34,$26,$24
DB $26,$24,$26,$24,$3E,$2C,$3C,$18

; End of NUMBERTILES.Z80
