; OTHERCHAR.Z80
;
; Tile Source File.
;
; Info:
;   Section              : Tiles
;   Bank                 : 0
;   Form                 : All tiles as one unit.
;   Format               : Gameboy 4 color.
;   Compression          : None.
;   Counter              : None.
;   Tile size            : 8 x 8
;   Tiles                : 0 to 7 + 1
;
;   Palette colors       : None.
;   SGB Palette          : None.
;   CGB Palette          : None.
;
;   Convert to metatiles : No.
;
; This file was generated by GBTD v2.2
;
;Indexes:
;   0:exclamation mark
;   1:Question mark
;   2:Period
;   3:TW
;   4:Vertical edge
;   5:corner
;   6:Horizontal edge
;   7:Cursor

;   8:space char


; Start of tile array.
OtherChar::
DB $00,$00,$30,$20,$30,$20,$30,$20
DB $30,$20,$30,$20,$20,$00,$30,$20
DB $00,$00,$38,$30,$7C,$48,$0C,$08
DB $18,$10,$18,$10,$10,$00,$18,$10
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$60,$40
DB $00,$00,$F0,$E0,$E0,$40,$79,$51
DB $7F,$55,$7F,$55,$5F,$1F,$1F,$00
DB $34,$24,$2C,$24,$34,$24,$2C,$24
DB $34,$24,$2C,$24,$34,$24,$2C,$24
DB $3C,$3C,$42,$7E,$81,$FF,$99,$E7
DB $99,$E7,$81,$FF,$42,$7E,$3C,$3C
DB $00,$00,$00,$00,$FF,$FF,$55,$00
DB $AA,$00,$FF,$FF,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$18,$18
DB $24,$3C,$42,$7E,$42,$7E,$42,$7E
;;spacechar
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$42,$63,$7E,$7F,$00,$7F

; End of OTHERCHAR.Z80
