; SPRITECURSOR.Z80
;
; Tile Source File.
;
; Info:
;   Section              : Tiles
;   Bank                 : 0
;   Form                 : All tiles as one unit.
;   Format               : Gameboy 4 color.
;   Compression          : None.
;   Counter              : None.
;   Tile size            : 8 x 8
;   Tiles                : 0 to 0
;
;   Palette colors       : None.
;   SGB Palette          : None.
;   CGB Palette          : None.
;
;   Convert to metatiles : No.
;
; This file was generated by GBTD v2.2


; Start of tile array.
CursorTile::
DB $00,$FF,$00,$81,$00,$81,$00,$81
DB $00,$81,$00,$81,$00,$81,$00,$C3

; End of SPRITECURSOR.Z80
